// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var DateTimePickerJsx = require("./react_components/dateTimePicker.jsx");

function make(selectedTime, onChange, children) {
  return ReasonReact.wrapJsForReason(DateTimePickerJsx.default, {
              selectedTime: selectedTime,
              onChange: onChange
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
