// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactGeosuggest = require("react-geosuggest");

((require('react-geosuggest/module/geosuggest.css')));

function make(onSuggestSelect, children) {
  return ReasonReact.wrapJsForReason(ReactGeosuggest.default, {
              onSuggestSelect: onSuggestSelect
            }, children);
}

exports.make = make;
/*  Not a pure module */
