// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var MapJsx = require("./react_components/map.jsx");

function make(selectedLocation, isochrones, children) {
  return ReasonReact.wrapJsForReason(MapJsx.default, {
              selectedLocation: selectedLocation,
              isochrones: isochrones
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
