// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("./map");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(layers, children) {
  return ReasonReact.wrapJsForReason($$Map, {
              layers: layers
            }, children);
}

exports.make = make;
/* ./map Not a pure module */
