// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var SelectJs = require("../node_modules/react-select/lib/Select.js");

((require('react-select/dist/react-select.css')));

function make(onChange, options, value, children) {
  return ReasonReact.wrapJsForReason(SelectJs.default, {
              onChange: onChange,
              options: options,
              value: value
            }, children);
}

exports.make = make;
/*  Not a pure module */
